require('kalimali.globals')
require("kalimali.telescope")
require("kalimali.lsp-config")
require('kalimali.lualine')
require('kalimali.harpoon')
require('kalimali.snippets')
-- require("kalimali.compe-config")
require('kalimali.treesitter')
require('kalimali.nvim_tree')
require('kalimali.bufferline')
require('kalimali.dashboard')
