require("kalimali.plugins")
require("kalimali.globals")
require("kalimali.autocmd")
require("kalimali.set")
require("kalimali.lualine")
require("kalimali.bufferline")
require("kalimali.dashboard")

require("kalimali.local_remaps")
require("kalimali.plugin_remaps")
